### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by laportem** [sfxcode/nuxt3-primevue-starter#12]
Awesome template; would be more complete if you add an internationalization package. If you don’t have time, which one you recommended.

**Comment by Kingside88** [comment]
First of all I want to give much credit to the author of this starter pack and keeping it up to date. Amazing work!
With this said I would like to provide some help to people.
i18n is a standard package for localization. In top of that is the package vue-18n build for vue: 
https://kazupon.github.io/vue-i18n/

How to use it with this starter pack:

install this package: 
`pnpm add vue-i18n`

Create a folder "locales"
Create you're localization files in there as json.
For example de.json:
```
{
    "save": "speichern",
    "delete": "löschen",
    "testSub": {
        "testSubKey": "meinTest"
    }
}
```
After then create another folder (If not exists): "plugins"
Create a file called "i18n.ts" in there:

```
import { createI18n } from 'vue-i18n'
import de from '../locales/de.json'
import en from '../locales/en.json'

const messages = {
  de: { ...de },
  en: { ...en },
}

let locales = ref<any>();

export const i18n = createI18n({
  legacy: false,
  locale: 'de', // Default locale
  fallbackLocale: 'en', // If locale is not exists use this
  localeDir: "locales", // Youre locales folder
  globalInjection: true,    
  messages
})

export default defineNuxtPlugin(async nuxtApp => {
  nuxtApp.vueApp.use(i18n)
})
```
Thats it.
Now you can use localization in template like this:
`$t("save")`
or
`$t("testSub.testSubKey")`

and in JavaScript:

```
import { useI18n } from "vue-i18n";
const { t } = useI18n();

let translation = t('testSub.testSubKey')
```

The last think: 
You may want to change locales.
In app/AppTopbar.vue you can add this simple locales select-option:

```
<OverlayPanel id="overlay_panel" ref="op" append-to="body" style="width: 200px">      
  <div class="locale-changer">
    <select v-model="$i18n.locale">
      <option v-for="locale in $i18n.availableLocales" :key="`locale-${locale}`" :value="locale">
        {{ locale }}
      </option>
    </select>
  </div>      
</OverlayPanel>
```

**Comment by Kingside88** [comment]
Thank you guys for thumbs up.
If you run an external REST API where you receive and send data from, than you may want receive the data in the language the user choses. In this case you have to append "Accept-Language" Header in you're request.
I created a composable which I use everywhere:
**composables\useGetFetch.ts**
```
 import { useI18n } from "vue-i18n";

export const useGetFetch = async (url : string, opts = {}) => {
  const { locale } = useI18n();
  const config = useRuntimeConfig();

  return $fetch(url, {
      ...opts,
      method: "GET",
      baseURL: config.API_BASE_URL,
      credentials: 'omit',
      headers: {
        'pragma': 'no-cache',
        'cache': 'no-cache',
        'cache-control': 'no-cache',
        'Expires': '0',
        'Accept-Language': locale.value
      },
      
  })
}
```
And use it like 
```
let personnel = ref(
  await useGetFetch(`personnel?personnelId=${route.params.id}`),
);
```

**Comment by sfxcode** [comment]
Thank you all for your input. I also would use @nuxtjs/i18n@next for now. Currently in beta but it works for me. If it is final it should be added to this project.

I close this issue for now.

Greetings,

Tom
