### ISSUE TITLE
yarn add primevue

### ISSUE THREAD

**Issue by breizhwave** [sfxcode/nuxt3-primevue-starter#21]
excellent work. But why package.json does not come with primevue ? any reason  ? here is my own package.json with latest nuxt by the way. Once again, excellent work 

`
{
  "name": "nuxt3-primevue-starter",
  "version": "1.3.1",
  "license": "MIT",
  "scripts": {
    "build": "nuxi build",
    "dev": "nuxi dev",
    "info": "nuxi info",
    "generate": "nuxi generate",
    "preview": "nuxi preview",
    "module": "nuxi init -t module my-module",
    "start": "node .output/server/index.mjs",
    "lint": "eslint --fix .",
    "test:ui": "vitest --ui",
    "test:unit": "vitest --run --reporter verbose",
    "test:coverage": "vitest run --coverage",
    "story:dev": "histoire dev",
    "story:build": "histoire build",
    "story:preview": "histoire preview"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^0.36.0",
    "@histoire/plugin-nuxt": "^0.15.8",
    "@histoire/plugin-vue": "^0.15.8",
    "@iconify-json/carbon": "^1.1.16",
    "@iconify-json/mdi": "^1.1.49",
    "@iconify-json/prime": "^1.1.5",
    "@iconify-json/twemoji": "^1.1.11",
    "@nuxt/content": "^2.5.2",
    "@nuxt/test-utils": "^3.2.3",
    "@pinia/nuxt": "^0.4.7",
    "@sfxcode/nuxt-primevue": "^1.0.3",
    "@unocss/nuxt": "^0.50.4",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vitest/ui": "^0.29.2",
    "@vueuse/nuxt": "^9.13.0",
    "c8": "^7.13.0",
    "eslint": "^8.35.0",
    "histoire": "^0.15.8",
    "jsdom": "^21.1.0",
    "nuxt": "^3.3",
    "sass": "^1.58.3",
    "typescript": "^4.9.5",
    "vitest": "^0.29.2"
  },
  "dependencies": {
    "primevue": "^3.25.0"
  }
}

`

**Comment by sfxcode** [comment]
Hi,

first of all thank you for your feedback and your nice words. I switched to pnpm long ago and have never looked back to yarn to be honest. No problem getting primevue on this way. 
I will look into this issue and will see if i can change the dependencies in @sfxcode/nuxt-primevue.

With the release of nuxt 3.3.1 today i will also update the @sfxcode/nuxt-primevue module soon.

Greetings,

Tom

**Comment by sfxcode** [comment]
Just released nuxt3-primevue-starter 1.3.2. Updated all to nuxt 3.3.1 and changed dependency syntax in sfxcode/nuxt-primevue (1.0.4). Like before, no problem witn pnpm, please try with your yarn installation if it resolves better now.

Otherwise give me some detail about your yarn version, maybe i can reproduce your problem.

Grat coding time,

Tom

**Comment by breizhwave** [comment]
thks, on yarn 1.22.19 it fails, but may be this is too old a yarn version I see we're getting near 34

https://github.com/yarnpkg/berry

error: 

 ERROR  Cannot start nuxt:  The "name" argument must be specified                                                                                                          13:42:58

  at new NodeError (node:internal/errors:399:5)
  at Performance.mark (node:internal/perf/performance:125:13)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:168:30)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:451:15)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2469:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6843:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6873:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)

**Comment by breizhwave** [comment]
apparently problem with nuxt3.3.1 not compatible with node 19

https://github.com/nuxt/nuxt/issues/19682

retrograde to nuxt3.2.3 brings another one 
 ERROR  No "exports" main defined in /Users/dourlaouen/Documents/FULLSTACK/webstorm/nuxt-wave/nuxt3-primevue-starter-main/nuxt3-primevue-starter-main/node_modules/@nuxt/kit/package.json

SOLUTION : switch bakc to node 18 LTS !! 
 
on mac I suggest nvm https://tecadmin.net/install-nvm-macos-with-homebrew/
