### ISSUE TITLE
histoire is not working

### ISSUE THREAD

**Issue by Kingside88** [sfxcode/nuxt3-primevue-starter#23]
I just want to mentian that histoire is not working.
I get the error
`RangeError: Maximum call stack size exceeded`

how to reproduce it? clone it, `pnpm install` and `pnpm run story:dev`

**Comment by sfxcode** [comment]
Hi,

thank you for reporting.

Definitly some issue with histoire at the moment. All my attempts to fix has failed, will look into it the next weekend.

Always a problem when trying to use latest packages that some components don't play nicely with each other.

Greetings,

Tom

**Comment by Kingside88** [comment]
I saw you did some updates a few hours ago.
When I start it now it shows this error:
`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

The problem lay on @histoire/plugin-nuxt.
Versions greater than 14.2 cause this problem.

To fix it for now we should stick with the older version. But don't know what else the update 15 effect.
`pnpm install @histoire/plugin-nuxt@0.14.2` did it for me. It also runs with histoire 0.15.9

**Comment by sfxcode** [comment]
Hi, thank you for your input.

I changed the version of @histoire/plugin-nuxt back to 0.14.2 and everything works as expected.

Hopefully this will be fixed in newer histoire versions.
