### ISSUE TITLE
Many typescript errors in VScode

### ISSUE THREAD

**Issue by laportem** [sfxcode/nuxt3-primevue-starter#24]
Although these are not run time issues but when you open the project in VSCode many areas of the project are throwing the typescript "Property 'X' does not exist on type 'Y'."

For example
In /pages/prime/datatable.vue, this code:

`filters.value = {
  global: { value: null, matchMode: FilterMatchMode.CONTAINS },
  name: { value: null, matchMode: FilterMatchMode.CONTAINS },
  code: { value: null, matchMode: FilterMatchMode.CONTAINS },
  inventoryStatus: { value: null, matchMode: FilterMatchMode.STARTS_WITH },
}`
is throwing 
Property 'CONTAINS' does not exist on type 'FilterMatchModeOptions'.

also this line
`<InputText v-model="filters.global.value" placeholder="Globale Suche" />`

throws
Property 'global' does not exist on type '{}'.

**Comment by sfxcode** [comment]
Because this problem is more a primevue typescript design problem and i can not solve it in this demo, i will close this issue for now
