### ISSUE TITLE
No Hot module reload (HMR)

### ISSUE THREAD

**Issue by Kingside88** [sfxcode/nuxt3-primevue-starter#28]
Is it only me or is hmr not working?
Tested with a clean installation with newest Edge Browser  Version 112.0.1722.39 (Offizielles Build) (64-Bit)
and Firefox 111.0.1 (64-bit).

Even if VS Code print this line in the terminal:
`ℹ hmr update /pages/index.vue (x3)`

**Comment by sfxcode** [comment]
Hi,

works fine for me. I am running on a Mac M2 Max on Chrome 112.0.5615.49. 
Some things seems to be broken in nuxt 3.4.0.
Updated to latest Patch release 3.4.1.

Maybe that solves your problem. 

Greetings,

Tom

**Comment by Kingside88** [comment]
unfortunately version 3.4.1 does not solve the problem. 
I should mention that I work on a windows 11 machine

**Comment by Kingside88** [comment]
I want to close this problem because it has nothing to do with this starter. I don't know who is really responsible for this problem. Vite? Nuxt? Vue? 
The point is, when a page or component is to big, HMR stops working. I can't say a size but its like that.
