### ISSUE TITLE
Histoire is broken

### ISSUE THREAD

**Issue by sfxcode** [sfxcode/nuxt3-primevue-starter#29]
Histoire 0.16 is actual broken.

[unocss-hmr] TypeError: __vite_ssr_import_meta__.hot.send is not a function

Created an issue https://github.com/unocss/unocss/issues in unocss,
maybe someone can help on this side.

**Comment by sfxcode** [comment]
Latest Version shows Error Messages for each Vue files:

At least one <template> or <script> is required in a single file component.  

Seems no correct source maps are available.

Maybe a problem with vite plugin vue:

[sourcemap to Vue SFC doesn't work on first load #130](https://github.com/vitejs/vite-plugin-vue/issues/130)

**Comment by Kingside88** [comment]
Latest version of storybook or histoire?

**Comment by sfxcode** [comment]
Histoire. Updated all dependencies, but still a lot of error messages like i wwrote before.

**Comment by sfxcode** [comment]
Actual Main problems:
- Nuxt Content seems to break
- Nuxt DevTools seems to break
- Nuxt 3.7 not working with Histoire

See: https://github.com/histoire-dev/histoire/issues/587

**Comment by Kingside88** [comment]
Maybe you think again about replacing it with storybook?
There is a nice module project for: https://storybook.nuxtjs.org/

**Comment by sfxcode** [comment]
Nuxt Content seems to break with storybook also - for now i remove histoire because it does not play with the other parts of this demo nicely together
