### ISSUE TITLE
Please create ~/components/content and restart the Nuxt server to use components in Markdown 

### ISSUE THREAD

**Issue by Kingside88** [sfxcode/nuxt3-primevue-starter#3]
man this is so awesome!
I just want to say thank you. 
It's just works together out of the box.
Maybe one little think: My console says the follow error, when I try to start it:

Please create ~/components/content and restart the Nuxt server to use components in Markdown

**Comment by sfxcode** [comment]
Hi,

thank you for your nice words.
I always hope that someone find this starter code useful ....

Warning is fixed now ;-) 
Added some demo code for hero component.

Commit:

https://github.com/sfxcode/nuxt3-primevue-starter/commit/1b776888e1f32e3a3df1c4fd4545bcf9e704fb3f
