### ISSUE TITLE
Copying auth pages from Sakai-vue

### ISSUE THREAD

**Issue by vinstah** [sfxcode/nuxt3-primevue-starter#31]
Hi i am trying to copy the vue files from Sakai-vue auth views (login.vue) but it doesn’t display right, i think because now using unocss not tailwind

**Comment by Kingside88** [comment]
Sounds like an issue with an implementation but not with this starter.

**Comment by sfxcode** [comment]
can not reproduce, sorry

**Comment by ironytr** [comment]
wish this project used tailwindcss instead of unocss hippie thing. now im trying to figure out how to translate free sakai pages to unocss wish me luck lol.
