### ISSUE TITLE
Unable to use Static Site Generation

### ISSUE THREAD

**Issue by SWATOPLUS** [sfxcode/nuxt3-primevue-starter#34]
Step to reproduce:
1. run `pnpm generate` (alias of `nuxi generate`)
2. run `pnpx serve .output/public`
3. Go to http://localhost:3000

Expected result: application loaded correctly
Actual result: 500 error displayed
![изображение](https://github.com/sfxcode/nuxt3-primevue-starter/assets/13176763/851e3620-a57e-471a-baaa-20d1c6db2f05)

**Solution**: update version of @nuxtjs/i18n

**Comment by sfxcode** [comment]
should work in latest version - thank you for your input
