### ISSUE TITLE
Migrate to ESLint Flat Config?

### ISSUE THREAD

**Issue by NamesMT** [sfxcode/nuxt3-primevue-starter#40]
- [x]  I could help with a PR if you don't have the time for it.

**Comment by NamesMT** [comment]
Actually, seems like [nuxt/eslint](https://github.com/nuxt/eslint) release for flat config haven't reached stable yet (still in alpha), could delay till it's confirmed stable.

**Comment by sfxcode** [comment]
Hi, thank you for pointing out. If there is a stable release, i will be happy when you take part with a PR.

Meanwhile, greetings and happy coding ...

**Comment by sfxcode** [comment]
switched to antfu eslint config and eslint 9
