### ISSUE TITLE
Mobile version is unusable since you migrated to primevue 4

### ISSUE THREAD

**Issue by klukiyan** [sfxcode/nuxt3-primevue-starter#41]
The persistent sidebar on mobile makes it unusable.

And also the overall interface both on PC and mobile used be nicer before

**Comment by sfxcode** [comment]
Hi, 
for me it is more a tech demo than a perfectly styled app to be honest.
Also unusable sounds a little bit hard imho.
If PrimeVue updates the free Sakai Theme to PrimeVue 4, i will look into it.
At the moment my intention is to help other people with the migration to PrimeVue 4.

Thanks for your input,

Tom

**Comment by klukiyan** [comment]
Yes, you are right. Probably I use your previous version for three production applications already wanted to use it again but this new version is quite true so I decided to pick one of the previous version instead thank you very much for a nicetemplate/boiler plate. Whatever we call it.
