### ISSUE TITLE
Pre-transform Error

### ISSUE THREAD

**Issue by mynameisjeffe** [sfxcode/nuxt3-primevue-starter#43]
## Describe the bug
Cloning from the latest repository seems to break. Likely related to integration with Formkit

### Reproduction:
https://stackblitz.com/~/github.com/mynameisjeffe/nuxt3-primevue-starter?file=.stackblitzrc
![image](https://github.com/user-attachments/assets/cad7f352-c9c1-4d7b-991b-db7e22235179)

![image](https://github.com/user-attachments/assets/e3d3ee57-4687-4001-a1ad-fc508a9404a9)

Steps:
1. Clone from main
2. Side Nav -> PrimeVue -> Validation

Observations:
1. This happens on both local and stackblitz
3. If I pin Nuxt to exact version 3.13.0, the error doesn't appear

Note: 
Please run with npm run dev.

### Used Package Manager
1. npm (Stackblitz)
2. pnpm (local)
4. bun (local)

### System Info
(Stackblitz)
system:   
  OS: Linux 5.0 undefined    
  CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz    
  Memory: 0 Bytes / 0 Bytes    Shell: 1.0 - /bin/jsh  Binaries:    
  Node: 18.20.3 - /usr/local/bin/node    
  npm: 10.2.3 - /usr/local/bin/npm    
  pnpm: 8.15.6 - /usr/local/bin/pnpm

(Local)
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 95.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh

 Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.26 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 128.1.69.162
    Firefox Nightly: 132.0a1

**Comment by sfxcode** [comment]
Should be done with the last releases ... if not please reopen issue

Greetings,

Tom
