### ISSUE TITLE
error 500 primevue not installed when ssr:true

### ISSUE THREAD

**Issue by robotpapier** [sfxcode/nuxt3-primevue-starter#5]
Hi,
does this starter works in ssr mode?
I have this message when I set it on true.

**Comment by sfxcode** [comment]
Hi,

had some issues with SSR and chart.js in primevue with ssr. Actual version is without chart.js and seems to work fine with ssr. Actual demo on netlify use ssr.

Hope it is working also for you,

Greetings Tom

**Comment by robotpapier** [comment]
Hi,
ok.
but is it normal that we have ssr:false in nuxt.config.ts ?

`export default defineNuxtConfig({
  ssr: false,`

when set to true it doesn't work.

**Comment by sfxcode** [comment]
Hi,

in the current version (0.6.3) ssr is set to true:

```export default defineNuxtConfig({
  ssr: true,
  runtimeConfig: {
    public: {
      APP_VERSION: pkg.version,
      APP_NAME: pkg.name,
    },
  },
```

and for me ssr seems to work fine (also published on netlify).

Maybe you have to clear node_modules and update dependencies to make it also work for you.
Tested on my Mac with Node 16 ...

Good luck,

Tom

**Comment by robotpapier** [comment]
yes it's working indeed, I wasn't using the right version ^^
thanks!
