### ISSUE TITLE
unocss bg classes not rendering

### ISSUE THREAD

**Issue by klukiyan** [sfxcode/nuxt3-primevue-starter#9]
Hi, 
Thank you for an amazing template.
For some reason I can't make the bg class to work correctly.

For example if `sombgcolor` = `bg-green-300`
```html
<Tag class="mr-2" value="Primary" :class="somebgcolor"></Tag>
```
First of all for some reason it renders the computed class twice and then doesn't color the element.
If I hardcode it - it sometimes works, sometimes doesn't. However with dynamic value it's always rendered twice in the dom and doesn't have any effect.

**Comment by sfxcode** [comment]
I will close this issue because it is out of scope for this starter project.

Hope that will be ok for you,

Greetings,

Tom
